import Foundation

public enum CustomerSharedTexts {
    private static let texts: [String: [String: String]] = [
        "en": [
            "active_order_fallback": "active order",
            "active_status": "active",
            "add_failed_template": "Add failed: {error}",
            "add_to_cart": "Add to cart",
            "added_template": "Added: {name}",
            "cart_error_template": "Cart error: {error}",
            "cart_section": "Cart",
            "checkout": "Checkout",
            "checkout_failed_template": "Checkout failed: {error}",
            "checkout_submitted_template": "Checkout submitted: {order}",
            "customer_shop_title": "Customer Shop",
            "device": "Device",
            "in_progress_status": "in progress",
            "items": "Items",
            "language": "Language",
            "language_section": "Language",
            "last_update": "Last update",
            "loading_failed_template": "Loading failed: {error}",
            "loading_shop": "Loading shop...",
            "location": "Location",
            "no_orders_yet": "No orders yet",
            "order_number_template": "Order #{id}",
            "orders_error_template": "Orders error: {error}",
            "orders_section": "Orders",
            "product_fallback": "Product",
            "products_section": "Products",
            "shop": "Shop",
            "shop_loaded": "Shop loaded",
            "status": "Status",
            "status_section": "Status",
            "total": "Total",
            "updated": "Updated"
        ],
        "de": [
            "active_order_fallback": "aktive Bestellung",
            "active_status": "aktiv",
            "add_failed_template": "Hinzufügen fehlgeschlagen: {error}",
            "add_to_cart": "In den Warenkorb",
            "added_template": "Hinzugefügt: {name}",
            "cart_error_template": "Warenkorbfehler: {error}",
            "cart_section": "Warenkorb",
            "checkout": "Zur Kasse",
            "checkout_failed_template": "Checkout fehlgeschlagen: {error}",
            "checkout_submitted_template": "Checkout gesendet: {order}",
            "customer_shop_title": "Kundenshop",
            "device": "Gerät",
            "in_progress_status": "in Bearbeitung",
            "items": "Artikel",
            "language": "Sprache",
            "language_section": "Sprache",
            "last_update": "Letzte Aktualisierung",
            "loading_failed_template": "Laden fehlgeschlagen: {error}",
            "loading_shop": "Shop wird geladen...",
            "location": "Standort",
            "no_orders_yet": "Noch keine Bestellungen",
            "order_number_template": "Bestellung #{id}",
            "orders_error_template": "Bestellfehler: {error}",
            "orders_section": "Bestellungen",
            "product_fallback": "Produkt",
            "products_section": "Produkte",
            "shop": "Shop",
            "shop_loaded": "Shop geladen",
            "status": "Status",
            "status_section": "Status",
            "total": "Gesamt",
            "updated": "Aktualisiert"
        ],
        "tr": [
            "active_order_fallback": "aktif sipariş",
            "active_status": "aktif",
            "add_failed_template": "Ekleme başarısız: {error}",
            "add_to_cart": "Sepete ekle",
            "added_template": "Eklendi: {name}",
            "cart_error_template": "Sepet hatası: {error}",
            "cart_section": "Sepet",
            "checkout": "Siparişi Tamamla",
            "checkout_failed_template": "Ödeme başarısız: {error}",
            "checkout_submitted_template": "Ödeme gönderildi: {order}",
            "customer_shop_title": "Müşteri Mağazası",
            "device": "Cihaz",
            "in_progress_status": "devam ediyor",
            "items": "Öğeler",
            "language": "Dil",
            "language_section": "Dil",
            "last_update": "Son güncelleme",
            "loading_failed_template": "Yükleme başarısız: {error}",
            "loading_shop": "Mağaza yükleniyor...",
            "location": "Konum",
            "no_orders_yet": "Henüz sipariş yok",
            "order_number_template": "Sipariş #{id}",
            "orders_error_template": "Sipariş hatası: {error}",
            "orders_section": "Siparişler",
            "product_fallback": "Ürün",
            "products_section": "Ürünler",
            "shop": "Mağaza",
            "shop_loaded": "Mağaza yüklendi",
            "status": "Durum",
            "status_section": "Durum",
            "total": "Toplam",
            "updated": "Güncellendi"
        ],
        "ar": [
            "active_order_fallback": "طلب نشط",
            "active_status": "نشط",
            "add_failed_template": "فشلت الإضافة: {error}",
            "add_to_cart": "أضف إلى السلة",
            "added_template": "تمت الإضافة: {name}",
            "cart_error_template": "خطأ في السلة: {error}",
            "cart_section": "السلة",
            "checkout": "إتمام الطلب",
            "checkout_failed_template": "فشل إتمام الطلب: {error}",
            "checkout_submitted_template": "تم إرسال إتمام الطلب: {order}",
            "customer_shop_title": "متجر العميل",
            "device": "الجهاز",
            "in_progress_status": "قيد التنفيذ",
            "items": "العناصر",
            "language": "اللغة",
            "language_section": "اللغة",
            "last_update": "آخر تحديث",
            "loading_failed_template": "فشل التحميل: {error}",
            "loading_shop": "جارٍ تحميل المتجر...",
            "location": "الموقع",
            "no_orders_yet": "لا توجد طلبات بعد",
            "order_number_template": "الطلب #{id}",
            "orders_error_template": "خطأ في الطلبات: {error}",
            "orders_section": "الطلبات",
            "product_fallback": "المنتج",
            "products_section": "المنتجات",
            "shop": "المتجر",
            "shop_loaded": "تم تحميل المتجر",
            "status": "الحالة",
            "status_section": "الحالة",
            "total": "الإجمالي",
            "updated": "تم التحديث"
        ],
        "ru": [
            "active_order_fallback": "активный заказ",
            "active_status": "активен",
            "add_failed_template": "Ошибка добавления: {error}",
            "add_to_cart": "Добавить в корзину",
            "added_template": "Добавлено: {name}",
            "cart_error_template": "Ошибка корзины: {error}",
            "cart_section": "Корзина",
            "checkout": "Оформить заказ",
            "checkout_failed_template": "Ошибка оформления заказа: {error}",
            "checkout_submitted_template": "Заказ оформлен: {order}",
            "customer_shop_title": "Магазин клиента",
            "device": "Устройство",
            "in_progress_status": "в процессе",
            "items": "Позиции",
            "language": "Язык",
            "language_section": "Язык",
            "last_update": "Последнее обновление",
            "loading_failed_template": "Ошибка загрузки: {error}",
            "loading_shop": "Загрузка магазина...",
            "location": "Локация",
            "no_orders_yet": "Заказов пока нет",
            "order_number_template": "Заказ #{id}",
            "orders_error_template": "Ошибка заказов: {error}",
            "orders_section": "Заказы",
            "product_fallback": "Товар",
            "products_section": "Товары",
            "shop": "Магазин",
            "shop_loaded": "Магазин загружен",
            "status": "Статус",
            "status_section": "Статус",
            "total": "Итого",
            "updated": "Обновлено"
        ]
    ]

    public static func text(_ language: String, _ key: String) -> String {
        let normalized = language.lowercased()
        return texts[normalized]?[key] ?? texts["en"]?[key] ?? key
    }
}
