name = "crm-delivery-android-api-worker"
main = "src/index.js"
compatibility_date = "2026-06-01"

routes = [
  { pattern = "api.horizend.com", custom_domain = true, zone_name = "horizend.com" }
]

[vars]
APP_NAME = "CRM Delivery Android API"
API_VERSION = "v1"

[[d1_databases]]
binding = "DB"
database_name = "crm-delivery-db"
database_id = "14103291-eb66-4a3d-9f84-585832a4b015"
