import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const ROOT = path.resolve(path.dirname(SCRIPT_PATH), "..");
const SOURCE = path.join(ROOT, "shared/i18n/admin_texts.json");
const OUTPUTS = Object.freeze({
  worker: path.join(ROOT, "cloudflare-worker/src/i18n/admin-shared.generated.js"),
  android: path.join(
    ROOT,
    "apps/admin-android/app/src/main/java/me/ayartuerk/crmadmin/ui/AdminSharedTexts.kt"
  ),
  apple: path.join(ROOT, "apple/shared/Sources/AdminSharedTexts.swift")
});
const LOCALES = Object.freeze(["en", "de", "tr", "ar", "ru"]);

function fail(message) {
  throw new Error(`admin i18n: ${message}`);
}

function validate(catalog) {
  if (!catalog || typeof catalog !== "object" || Array.isArray(catalog)) {
    fail("root must be an object");
  }
  const locales = Object.keys(catalog);
  if (locales.length !== LOCALES.length || locales.some((value, index) => value !== LOCALES[index])) {
    fail(`locales must be exactly ${LOCALES.join(", ")}`);
  }
  const englishKeys = Object.keys(catalog.en).sort();
  if (englishKeys.length === 0) fail("English catalog is empty");
  for (const locale of LOCALES) {
    const table = catalog[locale];
    if (!table || typeof table !== "object" || Array.isArray(table)) {
      fail(`${locale} must be an object`);
    }
    const keys = Object.keys(table).sort();
    if (keys.length !== englishKeys.length || keys.some((key, index) => key !== englishKeys[index])) {
      fail(`${locale} keys differ from English`);
    }
    for (const [key, value] of Object.entries(table)) {
      if (!/^[a-z][a-z0-9_]*$/.test(key)) fail(`${locale}.${key} has an invalid key`);
      if (typeof value !== "string" || !value.trim()) fail(`${locale}.${key} is empty`);
      if (/\u0000/.test(value)) fail(`${locale}.${key} contains a NUL character`);
    }
  }
  return catalog;
}

function kotlinString(value) {
  return JSON.stringify(value).replaceAll("$", "\\$");
}

function swiftString(value) {
  return JSON.stringify(value).replaceAll("\\u2028", "\\u{2028}").replaceAll("\\u2029", "\\u{2029}");
}

function workerModule(catalog) {
  return `// Generated by scripts/generate_admin_i18n.mjs. Do not edit by hand.\n`
    + `const AdminSharedTexts = ${JSON.stringify(catalog, null, 2)}\n;\n\n`
    + `export function getAdminSharedText(language = "en") {\n`
    + `  const lang = String(language || "en").toLowerCase();\n`
    + `  return AdminSharedTexts[lang] || AdminSharedTexts.en;\n`
    + `}\n`;
}

function kotlinModule(catalog) {
  const localeBlocks = LOCALES.map((locale) => {
    const entries = Object.entries(catalog[locale])
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, value]) => `            ${kotlinString(key)} to ${kotlinString(value)}`)
      .join(",\n");
    return `        ${kotlinString(locale)} to mapOf(\n${entries}\n        )`;
  }).join(",\n");
  return `// Generated by scripts/generate_admin_i18n.mjs. Do not edit by hand.\n`
    + `package me.ayartuerk.crmadmin.ui\n\n`
    + `internal object AdminSharedTexts {\n`
    + `    private val texts: Map<String, Map<String, String>> = mapOf(\n${localeBlocks}\n    )\n\n`
    + `    fun text(language: String, key: String): String {\n`
    + `        val selected = texts[language.lowercase()] ?: texts["en"].orEmpty()\n`
    + `        return selected[key] ?: texts["en"].orEmpty()[key] ?: key\n`
    + `    }\n}\n`;
}

function appleModule(catalog) {
  const localeBlocks = LOCALES.map((locale) => {
    const entries = Object.entries(catalog[locale])
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, value]) => `            ${swiftString(key)}: ${swiftString(value)}`)
      .join(",\n");
    return `        ${swiftString(locale)}: [\n${entries}\n        ]`;
  }).join(",\n");
  return `// Generated by scripts/generate_admin_i18n.mjs. Do not edit by hand.\n`
    + `import Foundation\n\n`
    + `public enum AdminSharedTexts {\n`
    + `    private static let texts: [String: [String: String]] = [\n${localeBlocks}\n    ]\n\n`
    + `    public static func text(_ language: String, _ key: String) -> String {\n`
    + `        let normalized = language.lowercased()\n`
    + `        return texts[normalized]?[key] ?? texts["en"]?[key] ?? key\n`
    + `    }\n}\n`;
}

export function loadAdminCatalog() {
  return validate(JSON.parse(fs.readFileSync(SOURCE, "utf8")));
}

export function generatedAdminOutputs(catalog = loadAdminCatalog()) {
  return Object.freeze({
    worker: workerModule(catalog),
    android: kotlinModule(catalog),
    apple: appleModule(catalog)
  });
}

export function generateAdminI18n() {
  const generated = generatedAdminOutputs();
  for (const [target, outputPath] of Object.entries(OUTPUTS)) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, generated[target], "utf8");
  }
  return generated;
}

if (process.argv[1] && path.resolve(process.argv[1]) === SCRIPT_PATH) {
  generateAdminI18n();
  process.stdout.write(`Generated shared Admin i18n for ${LOCALES.length} locales.\n`);
}

export { OUTPUTS, SOURCE };
